import Atmosphere from "@/components/Atmosphere";
import Globe from "@/components/Globe";
import Lights from "@/components/Lights";
import { OrbitControls } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import Head from "next/head";
import { Suspense } from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Explore Earth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Suspense fallback={<h1>Loading...</h1>}>
          <Canvas shadows>
            <Globe />
            <Atmosphere />
            <OrbitControls />
            <Lights />
          </Canvas>
        </Suspense>
      </main>
    </>
  );
}
